INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (1,'Zonderling','Zonderling description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (2,'Mr.Carmack','Mr.Carmack description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (3,'Frank Sinatra','Frank Sinatra description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (4,'Dean Martin','Dean Martin description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (5,'Crystal Castles','Crystal Castles description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (6,'Zeds Dead','Zeds Dead description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (7,'Kanye West','Kanye West description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (8,'Aphex Twin','Aphex Twin description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (9,'Danger','Danger description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (10,'Gorillaz','Gorillaz description');
INSERT INTO `stairway_sounds`.`artists`(`id_artist`,`pseudonym`, `description`) VALUES (11,'Chemical Brothers','Brothers description');